spring:
  application:
    name: notification-service
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: nguyenthang29tbdl@gmail.com
    password: mwfeispvymtsleew
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083

app:
  frontend:
    url: http://localhost:5173